import { Injectable } from '@nestjs/common';
import type {
  AIProvider,
  CanonicalChatRequest,
  ProviderEvent,
  ProviderCapabilities,
  ProviderGeneration,
  ProviderHealth,
  NormalizedUsage,
} from '@omniroute/provider-contracts';

class RunCancelledError extends Error {
  public constructor() {
    super('Run cancelled');
    this.name = 'RunCancelledError';
  }
}

const delay = (milliseconds: number): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, milliseconds));

/**
 * Deterministic development adapter. It implements the same canonical contract
 * as a future router-backed provider adapter and never receives credentials.
 */
@Injectable()
export class MockProvider implements AIProvider {
  public readonly id = 'fake' as const;
  private readonly cancelledRuns = new Set<string>();

  public async cancel(runId: string): Promise<void> {
    this.cancelledRuns.add(runId);
  }

  public async capabilities(
    request: CanonicalChatRequest,
  ): Promise<ProviderCapabilities> {
    void request;
    return { values: { streaming: true, text: true } };
  }

  public async generate(
    request: CanonicalChatRequest,
  ): Promise<ProviderGeneration> {
    let content = '';
    for await (const event of this.streamChat(request)) {
      if (event.type === 'content.delta') content += event.text;
    }
    return { content, usage: await this.usage(request) };
  }

  public async health(): Promise<ProviderHealth> {
    return { provider: this.id, status: 'ready' };
  }

  public stream(request: CanonicalChatRequest): AsyncIterable<ProviderEvent> {
    return this.streamChat(request);
  }

  public async usage(request: CanonicalChatRequest): Promise<NormalizedUsage> {
    void request;
    return {};
  }

  public async *streamChat(
    request: CanonicalChatRequest,
  ): AsyncIterable<ProviderEvent> {
    if (process.env.NODE_ENV === 'production')
      throw new Error('Mock execution is disabled in production');
    const providerRequestId = `mock-${request.runId}`;
    yield { providerRequestId, runId: request.runId, type: 'run.started' };

    const latestPrompt = [...request.context.messages]
      .reverse()
      .find((message) => message.role === 'user')?.content;
    const response = [
      `Mock ${request.modelKey} is responding to: ${latestPrompt ?? 'your message'}`,
      '',
      'This streamed reply is generated by OmniRoute’s provider-neutral mock adapter.',
    ].join('\n');

    for (const token of response.match(/\S+\s*/g) ?? []) {
      if (this.cancelledRuns.has(request.runId)) {
        this.cancelledRuns.delete(request.runId);
        throw new RunCancelledError();
      }
      await delay(18);
      yield { runId: request.runId, text: token, type: 'content.delta' };
    }

    yield {
      finishReason: 'stop',
      runId: request.runId,
      type: 'run.completed',
    };
    this.cancelledRuns.delete(request.runId);
  }

  public isCancellation(error: unknown): boolean {
    return error instanceof RunCancelledError;
  }
}
